apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-cbuq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-cbuq@sha256:10d2f5fbbeaaaf51043ac32a458f10c9fc15582d2f556334610a02c75642252e
        name: my-nodejs
        resources: {}
status: {}
